/*
 * generated by Xtext 2.10.0
 */
package com.veapps.dnn.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class DlsIdeaModule extends AbstractDlsIdeaModule {
}
