/**
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.ActivationFunctionType;
import org.xtext.example.mydsl.myDsl.Layer;
import org.xtext.example.mydsl.myDsl.LayerDeclaration;
import org.xtext.example.mydsl.myDsl.LayerType;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.WeightInitType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Layer</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LayerImpl#getLayerDecl <em>Layer Decl</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LayerImpl#getLayerType <em>Layer Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LayerImpl#getActivType <em>Activ Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LayerImpl#getWeightInit <em>Weight Init</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.LayerImpl#getBiasInit <em>Bias Init</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LayerImpl extends MinimalEObjectImpl.Container implements Layer
{
  /**
   * The cached value of the '{@link #getLayerDecl() <em>Layer Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLayerDecl()
   * @generated
   * @ordered
   */
  protected LayerDeclaration layerDecl;

  /**
   * The default value of the '{@link #getLayerType() <em>Layer Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLayerType()
   * @generated
   * @ordered
   */
  protected static final LayerType LAYER_TYPE_EDEFAULT = LayerType.CONVOLUTIONAL;

  /**
   * The cached value of the '{@link #getLayerType() <em>Layer Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLayerType()
   * @generated
   * @ordered
   */
  protected LayerType layerType = LAYER_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getActivType() <em>Activ Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivType()
   * @generated
   * @ordered
   */
  protected static final ActivationFunctionType ACTIV_TYPE_EDEFAULT = ActivationFunctionType.SIGMOID;

  /**
   * The cached value of the '{@link #getActivType() <em>Activ Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActivType()
   * @generated
   * @ordered
   */
  protected ActivationFunctionType activType = ACTIV_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getWeightInit() <em>Weight Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWeightInit()
   * @generated
   * @ordered
   */
  protected static final WeightInitType WEIGHT_INIT_EDEFAULT = WeightInitType.ZERO;

  /**
   * The cached value of the '{@link #getWeightInit() <em>Weight Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWeightInit()
   * @generated
   * @ordered
   */
  protected WeightInitType weightInit = WEIGHT_INIT_EDEFAULT;

  /**
   * The default value of the '{@link #getBiasInit() <em>Bias Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBiasInit()
   * @generated
   * @ordered
   */
  protected static final String BIAS_INIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBiasInit() <em>Bias Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBiasInit()
   * @generated
   * @ordered
   */
  protected String biasInit = BIAS_INIT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LayerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.LAYER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LayerDeclaration getLayerDecl()
  {
    return layerDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLayerDecl(LayerDeclaration newLayerDecl, NotificationChain msgs)
  {
    LayerDeclaration oldLayerDecl = layerDecl;
    layerDecl = newLayerDecl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYER__LAYER_DECL, oldLayerDecl, newLayerDecl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLayerDecl(LayerDeclaration newLayerDecl)
  {
    if (newLayerDecl != layerDecl)
    {
      NotificationChain msgs = null;
      if (layerDecl != null)
        msgs = ((InternalEObject)layerDecl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.LAYER__LAYER_DECL, null, msgs);
      if (newLayerDecl != null)
        msgs = ((InternalEObject)newLayerDecl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.LAYER__LAYER_DECL, null, msgs);
      msgs = basicSetLayerDecl(newLayerDecl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYER__LAYER_DECL, newLayerDecl, newLayerDecl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LayerType getLayerType()
  {
    return layerType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLayerType(LayerType newLayerType)
  {
    LayerType oldLayerType = layerType;
    layerType = newLayerType == null ? LAYER_TYPE_EDEFAULT : newLayerType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYER__LAYER_TYPE, oldLayerType, layerType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ActivationFunctionType getActivType()
  {
    return activType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setActivType(ActivationFunctionType newActivType)
  {
    ActivationFunctionType oldActivType = activType;
    activType = newActivType == null ? ACTIV_TYPE_EDEFAULT : newActivType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYER__ACTIV_TYPE, oldActivType, activType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WeightInitType getWeightInit()
  {
    return weightInit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWeightInit(WeightInitType newWeightInit)
  {
    WeightInitType oldWeightInit = weightInit;
    weightInit = newWeightInit == null ? WEIGHT_INIT_EDEFAULT : newWeightInit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYER__WEIGHT_INIT, oldWeightInit, weightInit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBiasInit()
  {
    return biasInit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBiasInit(String newBiasInit)
  {
    String oldBiasInit = biasInit;
    biasInit = newBiasInit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LAYER__BIAS_INIT, oldBiasInit, biasInit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYER__LAYER_DECL:
        return basicSetLayerDecl(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYER__LAYER_DECL:
        return getLayerDecl();
      case MyDslPackage.LAYER__LAYER_TYPE:
        return getLayerType();
      case MyDslPackage.LAYER__ACTIV_TYPE:
        return getActivType();
      case MyDslPackage.LAYER__WEIGHT_INIT:
        return getWeightInit();
      case MyDslPackage.LAYER__BIAS_INIT:
        return getBiasInit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYER__LAYER_DECL:
        setLayerDecl((LayerDeclaration)newValue);
        return;
      case MyDslPackage.LAYER__LAYER_TYPE:
        setLayerType((LayerType)newValue);
        return;
      case MyDslPackage.LAYER__ACTIV_TYPE:
        setActivType((ActivationFunctionType)newValue);
        return;
      case MyDslPackage.LAYER__WEIGHT_INIT:
        setWeightInit((WeightInitType)newValue);
        return;
      case MyDslPackage.LAYER__BIAS_INIT:
        setBiasInit((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYER__LAYER_DECL:
        setLayerDecl((LayerDeclaration)null);
        return;
      case MyDslPackage.LAYER__LAYER_TYPE:
        setLayerType(LAYER_TYPE_EDEFAULT);
        return;
      case MyDslPackage.LAYER__ACTIV_TYPE:
        setActivType(ACTIV_TYPE_EDEFAULT);
        return;
      case MyDslPackage.LAYER__WEIGHT_INIT:
        setWeightInit(WEIGHT_INIT_EDEFAULT);
        return;
      case MyDslPackage.LAYER__BIAS_INIT:
        setBiasInit(BIAS_INIT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.LAYER__LAYER_DECL:
        return layerDecl != null;
      case MyDslPackage.LAYER__LAYER_TYPE:
        return layerType != LAYER_TYPE_EDEFAULT;
      case MyDslPackage.LAYER__ACTIV_TYPE:
        return activType != ACTIV_TYPE_EDEFAULT;
      case MyDslPackage.LAYER__WEIGHT_INIT:
        return weightInit != WEIGHT_INIT_EDEFAULT;
      case MyDslPackage.LAYER__BIAS_INIT:
        return BIAS_INIT_EDEFAULT == null ? biasInit != null : !BIAS_INIT_EDEFAULT.equals(biasInit);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (layerType: ");
    result.append(layerType);
    result.append(", activType: ");
    result.append(activType);
    result.append(", weightInit: ");
    result.append(weightInit);
    result.append(", biasInit: ");
    result.append(biasInit);
    result.append(')');
    return result.toString();
  }

} //LayerImpl
