/**
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
