/*
 * generated by Xtext 2.10.0
 */
package com.veapps.dnn.idea.lang


class DlsFileType extends AbstractDlsFileType {
	public static final DlsFileType INSTANCE = new DlsFileType()
	
	new() {
		super(DlsLanguage.INSTANCE)
	}
}
