/**
 * generated by Xtext 2.11.0-SNAPSHOT
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Layer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Layer#getLayerDecl <em>Layer Decl</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Layer#getLayerType <em>Layer Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Layer#getActivType <em>Activ Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Layer#getWeightInit <em>Weight Init</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Layer#getBiasInit <em>Bias Init</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer()
 * @model
 * @generated
 */
public interface Layer extends EObject
{
  /**
   * Returns the value of the '<em><b>Layer Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Layer Decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layer Decl</em>' containment reference.
   * @see #setLayerDecl(LayerDeclaration)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer_LayerDecl()
   * @model containment="true"
   * @generated
   */
  LayerDeclaration getLayerDecl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Layer#getLayerDecl <em>Layer Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Layer Decl</em>' containment reference.
   * @see #getLayerDecl()
   * @generated
   */
  void setLayerDecl(LayerDeclaration value);

  /**
   * Returns the value of the '<em><b>Layer Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.LayerType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Layer Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layer Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.LayerType
   * @see #setLayerType(LayerType)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer_LayerType()
   * @model
   * @generated
   */
  LayerType getLayerType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Layer#getLayerType <em>Layer Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Layer Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.LayerType
   * @see #getLayerType()
   * @generated
   */
  void setLayerType(LayerType value);

  /**
   * Returns the value of the '<em><b>Activ Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.ActivationFunctionType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Activ Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activ Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.ActivationFunctionType
   * @see #setActivType(ActivationFunctionType)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer_ActivType()
   * @model
   * @generated
   */
  ActivationFunctionType getActivType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Layer#getActivType <em>Activ Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Activ Type</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.ActivationFunctionType
   * @see #getActivType()
   * @generated
   */
  void setActivType(ActivationFunctionType value);

  /**
   * Returns the value of the '<em><b>Weight Init</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.WeightInitType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Weight Init</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight Init</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.WeightInitType
   * @see #setWeightInit(WeightInitType)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer_WeightInit()
   * @model
   * @generated
   */
  WeightInitType getWeightInit();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Layer#getWeightInit <em>Weight Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight Init</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.WeightInitType
   * @see #getWeightInit()
   * @generated
   */
  void setWeightInit(WeightInitType value);

  /**
   * Returns the value of the '<em><b>Bias Init</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bias Init</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bias Init</em>' attribute.
   * @see #setBiasInit(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayer_BiasInit()
   * @model
   * @generated
   */
  String getBiasInit();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Layer#getBiasInit <em>Bias Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bias Init</em>' attribute.
   * @see #getBiasInit()
   * @generated
   */
  void setBiasInit(String value);

} // Layer
