/*
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl.validation

import org.eclipse.xtext.validation.Check
import org.xtext.example.mydsl.myDsl.MyDslPackage
import org.xtext.example.mydsl.myDsl.Network

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyDslValidator extends AbstractMyDslValidator {
	
	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkGreetingStartsWithCapital(Network greeting) {
		if (!Character.isUpperCase(greeting.name.charAt(0))) {
			error('Name should start with a capital', 
					MyDslPackage.Literals.NETWORK__NAME,
					INVALID_NAME)
		}
	}
	
}
